import {exp} from 'react-native-reanimated';

export const ACTION_INICIAR_SESION = 'ACTION_INICIAR_SESION';
export const ACTION_CAMBIAR_NOMBRE_USUARIO = 'ACTION_CAMBIAR_NOMBRE_USUARIO';

//Capacitaciones
export const ACTION_CAPACITACIONES_CARGANDO = 'ACTION_CAPACITACIONES_CARGANDO';
export const ACTION_CAPACITACIONES_CARGADAS = 'ACTION_CAPACITACIONES_CARGADAS';
export const ACTION_CAPACITACIONES_ERROR = 'ACTION_CAPACITACIONES_ERROR';

export const ACTION_CAPACITACION_CARGANDO = 'ACTION_CAPACITACION_CARGANDO';
export const ACTION_CAPACITACION_CARGADA = 'ACTION_CAPACITACION_CARGADA';
export const ACTION_CAPACITACION_ERROR = 'ACTION_CAPACITACION_ERROR';
export const ACTION_CAPACITACION_OBTENER_ACTIVIDAD =
  'ACTION_CAPACITACION_OBTENER_ACTIVIDAD';
export const ACTION_ACTIVIDAD_MARCAR_LEIDA = 'ACTION_ACTIVIDAD_MARCAR_LEIDA';
export const ACTION_ACTIVIDAD_MARCANDO_LEIDA =
  'ACTION_ACTIVIDAD_MARCANDO_LEIDA';
export const ACTION_ACTIVIDAD_SELECCIONAR_OPCION =
  'ACTION_ACTIVIDAD_SELECCIONAR_OPCION';

export const ACTION_ACTIVIDAD_MARCAR_ERROR_PREGUNTA =
  'ACTION_ACTIVIDAD_MARCAR_ERROR_PREGUNTA';
export const ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO =
  'ACTION_ATIVIDAD_ENVIAR_CUESTIONARIO';
export const ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_ERROR =
  'ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_ERROR';
export const ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_OK =
  'ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_OK';
