import {exp} from 'react-native-reanimated';

export const ACTION_INICIAR_SESION = 'ACTION_INICIAR_SESION';
export const ACTION_CAMBIAR_NOMBRE_USUARIO = 'ACTION_CAMBIAR_NOMBRE_USUARIO';

//Capacitaciones
export const ACTION_CAPACITACIONES_CARGANDO = 'ACTION_CAPACITACIONES_CARGANDO';
export const ACTION_CAPACITACIONES_CARGADAS = 'ACTION_CAPACITACIONES_CARGADAS';
export const ACTION_CAPACITACIONES_ERROR = 'ACTION_CAPACITACIONES_ERROR';

export const ACTION_CAPACITACION_CARGANDO = 'ACTION_CAPACITACION_CARGANDO';
export const ACTION_CAPACITACION_CARGADA = 'ACTION_CAPACITACION_CARGADA';
export const ACTION_CAPACITACION_ERROR = 'ACTION_CAPACITACION_ERROR';
export const ACTION_CAPACITACION_OBTENER_ACTIVIDAD =
  'ACTION_CAPACITACION_OBTENER_ACTIVIDAD';
export const ACTION_CAPACITACION_INC_PROGRESO =
  'ACTION_CAPACITACION_INC_PROGRESO';

export const ACTION_ACTIVIDAD_MARCAR_LEIDA = 'ACTION_ACTIVIDAD_MARCAR_LEIDA';
export const ACTION_ACTIVIDAD_MARCANDO_LEIDA =
  'ACTION_ACTIVIDAD_MARCANDO_LEIDA';
export const ACTION_ACTIVIDAD_SELECCIONAR_OPCION =
  'ACTION_ACTIVIDAD_SELECCIONAR_OPCION';

export const ACTION_ACTIVIDAD_MARCAR_ERROR_PREGUNTA =
  'ACTION_ACTIVIDAD_MARCAR_ERROR_PREGUNTA';
export const ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO =
  'ACTION_ATIVIDAD_ENVIAR_CUESTIONARIO';
export const ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_ERROR =
  'ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_ERROR';
export const ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_OK =
  'ACTION_ACTIVIDAD_ENVIAR_CUESTIONARIO_OK';
export const ACTION_ACTIVIDAD_INTENTO = 'ACTION_ACTIVIDAD_INTENTO';

export const ACTION_CLIENTS_LOADING = 'ACTION_CLIENTS_LOADING';
export const ACTION_CLIENTS_LOADED = 'ACTION_CLIENTS_LOADED';
export const ACTION_CLIENTS_ERROR = 'ACTION_CLIENTS_ERROR';
export const ACTION_CLIENTS_REMOVE = 'ACTION_CLIENTS_REMOVE';
export const ACTION_CLIENTS_EDIT = 'ACTION_CLIENTS_EDIT';
export const ACTION_CLIENTS_ADD = 'ACTION_CLIENTS_ADD';
export const ACTION_CLIENT_CLEAN = 'ACTION_CLIENT_CLEAN';

export const ACTION_CLIENT_LOADING = 'ACTION_CLIENT_LOADING';
export const ACTION_CLIENT_LOADED = 'ACTION_CLIENT_LOADED';
export const ACTION_CLIENT_ERROR = 'ACTION_CLIENT_ERROR';
export const ACTION_CLIENT_CHANGE_PROP = 'ACTION_CLIENT_CHANGE_PROP';

export const ACTION_CLIENT_SAVEING = 'ACTION_CLIENT_SAVEING';
export const ACTION_CLIENT_SAVED = 'ACTION_CLIENT_SAVED';
export const ACTION_CLIENT_SAVED_ERROR = 'ACTION_CLIENT_SAVED_ERROR';
export const ACTION_CLIENT_DELETING = 'ACTION_CLIENT_DELETING';
export const ACTION_CLIENT_DELETED = 'ACTION_CLIENT_DELETED';

export const ACTION_PRODUCTOS_CARGANDO = 'ACTION_PRODUCTOS_CARGANDO';
export const ACTION_PRODUCTOS_CARGADOS = 'ACTION_PRODUCTOS_CARGADOS';
export const ACTION_PRODUCTOS_ERROR = 'ACTION_PRODUCTOS_ERROR';

export const ACTION_PRODUCTOS_SET_METADATA = 'ACTION_PRODUCTOS_SET_METADATA';
export const ACTION_PRODUCTOS_CARGANDO_DETALLE =
  'ACTION_PRODUCTOS_CARGANDO_DETALLE';
export const ACTION_PRODUCTOS_DETALLE_CARGADO =
  'ACTION_PRODUCTOS_DETALLE_CARGADO';
export const ACTION_PRODUCTOS_ERROR_CARANDO_DETALLE =
  'ACTION_PRODUCTOS_ERROR_CARANDO_DETALLE';

export const ACTION_PRODUCTOS_CARGANDO_FORMULARIO =
  'ACTION_PRODUCTOS_CARGANDO_FORMULARIO';
export const ACTION_PRODUCTOS_FORMULARIO_CARGADO =
  'ACTION_PRODUCTOS_FORMULARIO_CARGADO';
export const ACTION_PRODUCTOS_ERROR_CARANDO_FORMULARIO =
  'ACTION_PRODUCTOS_ERROR_CARANDO_FORMULARIO';
